name: Checkmarx-AST Github Action

on:
  workflow_dispatch:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      
      # Checkmarx One CLI Action step
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref }}
          cx_tenant: dxc-beam-suntory
          base_uri: https://us.ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        continue-on-error: true # Allows the job to continue even if this step fails
        id: checkmarx-scan

      # Step to check if the previous step failed
      - name: Check Scan Status
        if: steps.checkmarx-scan.outcome == 'failure'
        run: |
          echo "Checkmarx scan failed. Review required before proceeding."
          echo "Scan details can be reviewed in the Checkmarx portal."
          exit 1 # This will cause the job to fail explicitly due to scan failure

      # Subsequent step that would run if the scan doesn't fail (or if continue-on-error is true)
      - name: Subsequent Step
        run: |
          echo "This step runs after the Checkmarx scan. It can be any step, like deploying to a test environment."
